### PR TITLE
change lastexecutionend to lastexecutionstart for avoid lost data

### PR DESCRIPTION
**Pull request by dengshilong**

### CODE REVIEW

**Comment by jprante** [comment]
Thanks! Great how you dig into the code.

**Comment by dengshilong** [comment]
I don't if this is a good method to solve the schedule problem, but it just
work. The debug info is very useful anyway.

2016-03-31 18:07 GMT+08:00 Jörg Prante <notifications@github.com>:

**Comment by dengshilong** [comment]
I don't know whether it is a good method to solve the schedule problem, but
it just work. The debug info is very useful anyway.

2016-03-31 18:11 GMT+08:00 邓世龙 <dengshilong1988@gmail.com>:

**Comment by jprante** [comment]
The schedule code as it exists is not very good and needs overhaul. Better a solution now than nothing. Thanks again!

**Comment by dengshilong** [comment]
Haha, you are welcome! I am new to ElasticSearch, your jdbc-importer save
me a lot of time.

2016-03-31 18:18 GMT+08:00 Jörg Prante <notifications@github.com>:

**Pull request merged**
