### PR TITLE
Support for partial updates

### PR DESCRIPTION
**Pull request by msimons**
Support for partial updates with optype = 'update'.

This pull request is fully dependent on elasticsearch-support pull request: https://github.com/jprante/elasticsearch-support/pull/2

### CODE REVIEW

**Comment by msimons** [comment]
all checks have failed because elasticsearch-support with version 1.7.2.1 isn't build/merged yet.

**Comment by jprante** [comment]
JDBC importer 1.7.2.1 is released which supports new `_optype` `update` to execute UpdateAction on ES bulk processor.

**Comment by msimons** [comment]
Thanks Jörg!

**Comment by sam1969** [comment]
Please give an example of implementation of "update". I have a document that is loaded in the elastic. A separate request I need to do in this document partial update - to change the value of one field. I make a request with:

SELECT
-868204 _id,
'update' _optype,
123.12 Rest

Rest - field to update.

I get a runtime error:

[ERROR] [BulkTransportClient] [elasticsearch [importer] [listener] [T # 1]] bulk [1] error
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: script or doc is missing;
at org.elasticsearch.action.bulk.BulkRequest.validate (BulkRequest.java:482) ~ [elasticsearch-jdbc-1.7.2.1-uberjar.jar :?]

The script setting the following:

    "jdbc": {
"driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver", 
        "url": "jdbc: sqlserver: // localhost: 1433; databasename = catalog", 
        "user": "elasticsearch", 
        "password": "elasticsearch", 
"autocommit": true, 
"strategy": "simple", 
        "sql": [{
"statement": "exec dbo.ES_GetArtRest2", 
  "callable": true 
}] ^
        "treat_binary_as_string": true, 
        "elasticsearch": {
             "cluster": "elasticsearch", 
             "host": "localhost", 
             "port": 9300 
        }, 
    "type": "Product2", 
        "index": "articles2" 
}

**Comment by jprante** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html 

You have to provide a `script` or `doc`. 

Example `doc.Rest` if `Rest` is the field to update.

Use at your own risk. I am not familiar with updates and I do not use them for various reasons in ES (one is, they do not work reliable in all situations) so I will not document this in JDBC importer because I don't want to get blamed for failures.

**Comment by sam1969** [comment]
doc.Rest did not work. The error remains the same. I do not want to build your application with Update API for partial update of documents and wanted to try it JDBC.

**Pull request closed without merging**
